<script setup lang="ts">
import { ref } from 'vue'
import familyPhoto from './assets/gammad-family.jpeg'
import familyPhoto2 from './assets/Family Picture 2.JPG?url'
import philippinesMap from './assets/philippines-map.svg'
import nursingHomePhoto from './assets/nursing home preaching 1.jpeg'
import bibleHandoutPhoto from './assets/bible handout.jpeg'
import bibleHandoutPhoto2 from './assets/bible handout 2.jpeg'
import bibleStudyPhoto from './assets/preaching at bible study.JPEG?url'
import graduationPhoto from './assets/graduation pic with Pastor.JPEG?url'
import holyweekPhoto from './assets/holyweek-pilgrims-to-antipolo cathedral.jpg'
import garmentPhoto from './assets/preaching at garment factory.JPG?url'
import preachingYouthPhoto from './assets/preaching at youth fellowship.JPG?url'
import youthPhoto from './assets/Youth fellowship.JPG?url'
import doorToDoorPhoto from './assets/door to door soul winning.JPG?url'

type Modal = 'rommel' | 'shiela' | 'ryle' | 'calling' | null
const menuOpen = ref(false)
const activeModal = ref<Modal>(null)
const closeMenu = () => (menuOpen.value = false)
const openModal = (modal: Exclude<Modal, null>) => (activeModal.value = modal)
const navigation = [['Home', '#home'], ['Salvation', '#salvation'], ['Calling', '#calling'], ['Vision', '#vision'], ['Prayer', '#prayer'], ['Support', '#support'], ['Contact', '#contact']]
</script>

<template>
  <header class="site-header">
    <a class="brand" href="#home" @click="closeMenu"><span class="brand-kicker">Pray for the</span><span class="brand-name"><strong>Gammad</strong><span>Family</span></span></a>
    <button class="menu-toggle" type="button" :aria-expanded="menuOpen" aria-controls="site-navigation" @click="menuOpen = !menuOpen"><span></span><span></span><span></span><span class="sr-only">Toggle navigation</span></button>
    <nav id="site-navigation" :class="{ open: menuOpen }" aria-label="Main navigation"><a v-for="[label, href] in navigation" :key="href" :href="href" @click="closeMenu">{{ label }}</a><a class="nav-give" href="#support" @click="closeMenu">Partner With Us</a></nav>
  </header>

  <main>
    <section id="home" class="hero section-shell">
      <img class="philippines-silhouette" :src="philippinesMap" alt="" aria-hidden="true" />
      <div class="hero-copy"><p class="eyebrow">Missionaries to the Philippines</p><h1>For the harvest.</h1><p class="hero-intro">We are Rommel, Shiela, and Ryle Gammad, called by God to reach the Philippines with the Gospel of Jesus Christ.</p><div class="hero-actions"><a class="button button-gold" href="#prayer">Pray With Us</a><a class="button button-outline" href="#vision">Our Vision <span aria-hidden="true">↓</span></a></div><blockquote><span class="quote-mark">“</span><div><p>The harvest truly is plenteous, but the labourers are few; Pray ye therefore the Lord of the harvest, that he will send forth labourers into his harvest.<span class="quote-end">”</span></p><cite>Matthew 9:37-38</cite></div></blockquote></div>
      <figure class="hero-art"><img :src="familyPhoto" alt="Rommel, Shiela, and Ryle Gammad" /><figcaption>Rommel <i></i> Shiela <i></i> Ryle</figcaption></figure>
    </section>

    <section id="salvation" class="salvation section-shell section-cream">
      <div class="salvation-top"><div class="section-heading"><p class="eyebrow">Our Stories</p><h2>Saved by grace.<br />Sent in faith.</h2></div><div class="salvation-copy prose"><p>We are the Gammad family from Elgin, Illinois. God saved us by His grace and has led us to surrender our lives to serve Him full-time as missionaries to the Philippines.</p><p>Our burden is for people to hear the true Gospel, grow as faithful disciples of Christ, and become part of Bible-believing churches.</p></div><aside class="belief-card"><span class="card-icon" aria-hidden="true">✦</span><p class="eyebrow">Our foundation</p><p>Jesus Christ alone saves, and God's Word is the final authority for faith and life.</p></aside><figure class="salvation-photo"><img :src="familyPhoto2" alt="The Gammad family" /></figure></div>
      <div class="testimony-grid">
        <article><span class="initial">R</span><h3>Rommel</h3><p>I was saved in 2004 in the Philippines at the age of 25. Over the years, God prepared my heart for ministry through preaching, devotions, prayer, conferences, and opportunities to serve.</p><p>For twenty-five years, I built a good career and enjoyed a comfortable life that was difficult to leave, but I came to realize that following God's will offers far greater security and satisfaction.</p><p>In January 2026, I left my career and surrendered to serve Him full-time as a missionary to the Philippines.</p><button class="text-link" type="button" @click="openModal('rommel')">Read full testimony →</button></article>
        <article><span class="initial">S</span><h3>Shiela</h3><p>I grew up in a Catholic background and was invited many times to attend a Baptist church by a coworker who later became a dear friend.</p><p>In June 1998, she invited me to a youth camp, where I heard a message about hell and realized my need for salvation. A lady showed me from the Bible how I could be saved, and that day I accepted Jesus Christ as my personal Saviour.</p><p>Although I did not immediately grow in my faith, in 2004 I gained assurance of my salvation, followed the Lord in baptism, and began faithfully attending a Bible-believing Baptist church.</p><button class="text-link" type="button" @click="openModal('shiela')">Read full testimony →</button></article>
        <article><span class="initial">R</span><h3>Ryle</h3><p>Ryle accepted Christ as his Saviour at the age of seven and is growing with his family as they prepare to serve in the Philippines.</p><button class="text-link" type="button" @click="openModal('ryle')">Read full testimony →</button></article>
      </div>
    </section>

    <section id="calling" class="calling section-shell section-calling">
      <div class="calling-overview">
        <div class="section-heading"><p class="eyebrow">God's call on our lives</p><h2>Every step prepared<br />the way forward.</h2></div>
        <div class="calling-note prose"><p>After twenty-five years in a career that brought security and comfort, God made His direction clear. On January 21, 2026, our family surrendered to follow His call into full-time missions.</p><button class="text-link" type="button" @click="openModal('calling')">Read full story →</button></div>
      </div>
      <div class="calling-body">
        <ol class="timeline"><li><strong>2004</strong><span>Rommel saved by God's grace</span></li><li><strong>2019</strong><span>Joined Northwest Bible Baptist Church</span></li><li><strong>2020</strong><span>God renewed a burden for ministry</span></li><li><strong>2025</strong><span>Ministry training at Providence Baptist College</span></li><li><strong>2026</strong><span>Surrendered to full-time missions in the Philippines</span></li></ol>
        <div class="calling-photos"><figure><img :src="graduationPhoto" alt="The Gammad family with a pastor" /></figure></div>
      </div>
      <div class="calling-gallery"><figure><img :src="nursingHomePhoto" alt="Preaching in a nursing home ministry" /><figcaption>Teaching the Word</figcaption></figure><figure><img :src="bibleHandoutPhoto" alt="Handing out Bibles" /><figcaption>Sharing the Gospel</figcaption></figure><figure><img :src="bibleHandoutPhoto2" alt="Handing out Bibles in the community" /><figcaption>Sharing the Gospel</figcaption></figure><figure><img :src="bibleStudyPhoto" alt="Sharing God's Word in a Bible study" /><figcaption>Sharing the Gospel</figcaption></figure></div>
    </section>

    <section id="vision" class="vision section-shell">
      <div class="vision-intro"><p class="eyebrow">Why the Philippines?</p><h2>A great need.<br />A willing family.</h2><p>In the summers of 2024 and 2025, our family visited the Philippines. During those trips, I had opportunities to share the Gospel with old friends and acquaintances, factory workers, police officers, hospital workers, and many others. I witnessed God working in hearts and saw a genuine hunger among Filipinos for the truth of His Word. God used these experiences to open my eyes to the great need for laborers and renewed my desire to serve Him full-time.</p><p>The Philippines is home to more than 117 million people. It is a deeply religious nation, yet many are deeply rooted in a false gospel of works-based salvation rather than faith in Jesus Christ alone.</p><p>According to the 2020 Census, 78.8 percent identified as Roman Catholic, 6.4 percent as Muslim, 4.8% as Evangelical, and 2.6% as Iglesia ni Cristo, while Bible Baptist Church accounted for only 0.5%. There are millions of people who still need to hear the Gospel.</p><p>God has used faithful American missionaries and raised up many Filipino Baptist preachers and missionaries. We believe there remains a tremendous need for independent, fundamental Baptist churches that faithfully proclaim the Gospel, stand firmly on the authority of Scripture, actively engage in soul winning, and carry out the Great Commission.</p></div>
      <div class="vision-media"><figure class="vision-photo-tall"><img :src="holyweekPhoto" alt="Pilgrims gathered at Antipolo Cathedral" /><figcaption>A deeply religious nation</figcaption></figure><figure><img :src="doorToDoorPhoto" alt="Door-to-door soul winning" /><figcaption>Opportunities to share Christ</figcaption></figure></div>
      <div class="vision-list"><p class="eyebrow">Our ministry vision</p><article><span>01</span><div><h3>Reach</h3><p>Proclaim the Gospel through soul winning, preaching, and outreach.</p></div></article><figure class="vision-work"><img :src="garmentPhoto" alt="Preaching at a garment factory" /></figure><article><span>02</span><div><h3>Plant</h3><p>Establish independent, fundamental, Bible-believing Baptist churches.</p></div></article><figure class="vision-work"><img :src="preachingYouthPhoto" alt="Preaching at a youth fellowship" /></figure><article><span>03</span><div><h3>Disciple</h3><p>Teach believers to grow in the Word and become faithful servants.</p></div></article><figure class="vision-work"><img :src="youthPhoto" alt="Youth fellowship" /></figure><article><span>04</span><div><h3>Train</h3><p>Equip faithful workers for a lasting ministry and a continuing harvest.</p></div></article></div>
    </section>

    <section id="prayer" class="prayer section-shell section-navy"><div class="section-heading light-heading"><p class="eyebrow">Please pray for</p><h2>Labourers for<br />the harvest.</h2></div><ol class="prayer-list"><li>A specific area and location to serve</li><li>A church building and start-up fund</li><li>Wisdom, good health, and safety during deputation</li><li>Churches to partner with us</li><li>Salvation and discipleship of lost souls</li></ol><a class="button button-gold" href="mailto:gammadtophilippines@gmail.com?subject=We%20are%20praying%20for%20you">Tell Us You Are Praying</a></section>
    <section id="support" class="support section-shell section-gold"><div><p class="eyebrow">Partner with us</p><h2>Together, we can reach the Philippines for Christ.</h2></div><div class="support-copy"><p>Your prayers, encouragement, and financial support make this ministry possible. Thank you for considering a partnership with our family.</p><a class="button button-navy" href="mailto:gammadtophilippines@gmail.com?subject=Support%20the%20Gammad%20Family">Ask About Supporting</a></div></section>
    <section id="contact" class="contact section-shell section-cream"><div class="section-heading"><p class="eyebrow">Contact us</p><h2>Let's connect.</h2></div><address><a href="mailto:gammadtophilippines@gmail.com"><span>Email</span> gammadtophilippines@gmail.com</a><a href="tel:+17738071597"><span>Phone</span> 773-807-1597</a><p><span>Sending church</span> Northwest Bible Baptist Church<br />9N889 Nesler Road, Elgin, IL 60124</p><p><span>Mission board</span> Northwest Bible Baptist Missions<br />9N889 Nesler Road, Elgin, IL 60124</p></address></section>
  </main>
  <footer><p>© {{ new Date().getFullYear() }} The Gammad Family</p><p>Missionaries to the Philippines</p><a href="#home">Back to top ↑</a></footer>

  <div v-if="activeModal" class="modal-backdrop" role="presentation" @click.self="activeModal = null"><section class="modal" role="dialog" aria-modal="true" :aria-labelledby="`${activeModal}-title`"><button class="modal-close" type="button" aria-label="Close" @click="activeModal = null">×</button>
    <template v-if="activeModal === 'rommel'"><p class="eyebrow">Rommel's testimony</p><h2 id="rommel-title">Saved by grace</h2><p>I grew up in a Catholic family. At a young age, I simply followed the religion of my parents. I served as an altar boy and was active in the Catholic youth group. I even participated in religious ceremonies, including carrying a cross in an Easter procession, believing that these religious activities could somehow help me get to heaven.</p><p>My eldest sister was the first in our family to be saved. I attended Baptist church services and heard the Gospel while I was in high school, but I never truly understood what it meant to be saved.</p><p>During college and the years that followed, I developed sinful habits and a worldly lifestyle, but after losing my father, God began to soften my heart and draw me to Himself.</p><p>One day, God used a daily devotional about salvation to show me my true spiritual condition. I realized that I was a sinner and that my religion, good works, and religious activities could never save me. I needed Jesus Christ.</p><p>In 2004, one morning while sitting at my desk in the office, I bowed my head and asked God to save me. I placed my faith in Jesus Christ and trusted Him alone for my salvation.</p><p>Not long afterward, I brought my mother and siblings to Alpha Baptist Church. God continued to work in their hearts, and eventually every one of them was saved. Our family was baptized together.</p><p><em>“For by grace are ye saved through faith; and that not of yourselves: it is the gift of God.” Ephesians 2:8</em></p></template>
    <template v-else-if="activeModal === 'shiela'"><p class="eyebrow">Shiela's testimony</p><h2 id="shiela-title">A faithful invitation</h2><p>I am thankful for a coworker who eventually became one of my good friends. She faithfully invited me to church many times, but because I grew up in a Catholic background, I always found reasons not to go.</p><p>One day, she invited me to attend a youth camp. As a young lady who loved the outdoors, I was finally convinced to go.</p><p>I still remember the preaching at that camp. The message was about hell, and it caused me to seriously consider where I would spend eternity. A lady sat down with me and showed me from the Bible how I could be saved. In June of 1998, I accepted Jesus Christ as my personal Saviour.</p><p>Although I had trusted Christ, I did not immediately grow in my faith. Then, in 2004, God helped me gain assurance of my salvation. I followed the Lord in baptism and began faithfully attending a Bible-believing Baptist church, where I started growing in my relationship with the Lord.</p><p>I am especially thankful that God used the persistence and faithfulness of a friend who never stopped inviting me to church.</p></template>
    <template v-else-if="activeModal === 'ryle'"><p class="eyebrow">Ryle's testimony</p><h2 id="ryle-title">Assurance in Christ</h2><p>When I was six years old, I remember hearing about salvation, but I never really knew what it meant. Coming home from church one night, I asked my dad what it meant to be saved. He took me through the Gospel and I made a profession of faith that day.</p><p>Coming to Northwest Bible Baptist Church was a big change for me. I had never felt conviction in my life before, so I doubted my salvation. All the way up until 2022, I felt fear and insecurity about where I would go when I died.</p><p>At football camp in August of 2022, Bro. Nichols preached a powerful message on hell. It was not until Thursday night of that week that God moved in my heart and I went forward for assurance. Bro. Jeremy Huston dealt with me, I got my assurance, and I have never doubted since that day.</p></template>
    <template v-else><p class="eyebrow">God's call on our lives</p><h2 id="calling-title">The full story</h2><p>In 2005, I enrolled in Bible college but was unable to finish my first semester when God opened the door for me to move to the United States. In 2006, Shiela and I got married. For the next thirteen years, we were members of a Baptist church in Schaumburg, Illinois, where I taught a Filipino Sunday School class and served as a deacon.</p><p>In 2019, my family and I began attending Northwest Bible Baptist Church. In the following year, while attending the Providence Baptist College graduation, God renewed my burden for ministry. When Dr. Keith Gomez said, “There is something about finishing what you started,” those words deeply convicted me.</p><p>Over the next few years, God continued preparing my heart. We faithfully participated in soul winning, discipleship, and other ministries in our church. Through missions conferences, conversations with missionaries, and summer trips to the Philippines, my desire for ministry became stronger.</p><p>With my pastor's encouragement and God's provision, I enrolled in Providence Baptist College in January 2025 to pursue a Master's degree in Biblical Studies. I began teaching a Tagalog Sunday School class and preaching regularly in our nursing home ministry.</p><p>As I balanced work, school, family, and ministry, I began earnestly praying that God would clearly show me His will concerning full-time ministry.</p><p>For twenty-five years, I had built a good career and enjoyed financial security. In January 2026, God brought the story of Abraham in Genesis 12 to my heart. I came to realize that following God's will would require me to trust Him beyond what was comfortable and secure.</p><p>That same month, my company announced a departmental restructuring. Because I had already expressed my desire to leave and pursue missions, I volunteered to be included in the workforce reduction. I had a deep sense of peace, knowing that God had answered my prayer and opened the door for me to follow His will. On January 21, 2026, my family and I surrendered to full-time missions.</p></template>
  </section></div>
</template>
